//
// Created by 宋晓奎 on 2023/12/21.
//

#ifndef MEMORYMODELANDNAMESPACE_DYNAMIC_MEMORY_H
#define MEMORYMODELANDNAMESPACE_DYNAMIC_MEMORY_H

#endif //MEMORYMODELANDNAMESPACE_DYNAMIC_MEMORY_H

extern double* free_ptr;