//
// Created by austsxk on 2023/12/20.
//

#ifndef MEMORYMODELANDNAMESPACE_LANGUAGE_LINK_H
#define MEMORYMODELANDNAMESPACE_LANGUAGE_LINK_H

#include "stdio.h"

#endif //MEMORYMODELANDNAMESPACE_LANGUAGE_LINK_H

